class_name UIVisualTokens
extends RefCounted

## Shared typography and stroke decisions for runtime and editor UI.
## Component-specific geometry remains beside the component that renders it.

const OUTLINE_PIXELS := 2.0
const BUILDING_ICON_STROKE_PIXELS := 4.0
const COMPASS_DIAMETER_PIXELS := 72
const TOOLBAR_BUTTON_PIXELS := 44.0
const ICON_NUMBER_COMPACT_ICON_PIXELS := 10.0
const CONSTRUCTION_MATERIAL_ICON_BASE_PIXELS := 20.0
const ICON_NUMBER_DEFAULT_SEPARATION_PIXELS := 2
const ICON_NUMBER_COMPACT_SEPARATION_PIXELS := 4

const SPEECH_BUBBLE_TEXT_FONT_SIZE := 9
const TOOLTIP_FONT_SIZE := 14

const BLUEPRINT_EDITOR_MODE_FONT_SIZE := 16
const BLUEPRINT_EDITOR_INSTRUCTIONS_FONT_SIZE := 14
const BLUEPRINT_EDITOR_STATUS_FONT_SIZE := 15

const SELECTION_COUNT_FONT_SIZE := 11
const DAY_COUNT_FONT_SIZE := 16
const DEBUG_TITLE_FONT_SIZE := 24
const DEBUG_INSTRUCTIONS_FONT_SIZE := 15
const DEBUG_READOUT_FONT_SIZE := 17
const BUILD_STAMP_FONT_SIZE := 12
const BUILDING_HOTKEY_FONT_SIZE := 14
const POPULATION_COUNT_FONT_SIZE := 22
const PILE_RESOURCE_COUNT_FONT_SIZE := 14
const CONSTRUCTION_NAME_FONT_SIZE := 16
const CONSTRUCTION_MATERIAL_FONT_SIZE := 14
const WORLD_TOOLTIP_FONT_SIZE := 16
const ONBOARDING_TITLE_FONT_SIZE := 20
const ONBOARDING_BODY_FONT_SIZE := 13
const COUNT_BADGE_FONT_SIZE := 18
